### ISSUE TITLE
Unexpected error in `elm-format` when snippet includes `'\r'` 

### ISSUE THREAD

**Issue by edkelly303** [lue-bird/elm-review-documentation-code-snippet#5]
This code snippet:
```elm
{-|

    '\r'

    --> '\r'

-}
check =
    0
```

Produces this error when running `elm-review --rules Review.Documentation.CodeSnippet --fix`

```bash
I got an unexpected error when running elm-format:

Unable to parse file <STDIN>:18:11 To see a detailed explanation, run elm make on the file.
```
I think maybe it is because `'\r'` does not get escaped properly, so it inserts a line break in the generated test.

**Comment by lue-bird** [comment]
I've identified and reported this as [an issue in the library we use for printing an AST](https://github.com/the-sett/elm-syntax-dsl/issues/50).

My immediate plans would be to temporarily patch this issue only for `\r` for now and because `\u{hex code}` is a bit more involved wait for the fix from our printing library?

I _could_ do the \u as well if you need it sooner, so tell me if that's the case.

**Comment by edkelly303** [comment]
Wonderful, thank you! I am completely happy to wait until this is addressed upstream; the fix isn't really important for anything I'm working on, I just noticed the issue in passing while I was writing some tests.

**Comment by lue-bird** [comment]
new version with upgraded dependency published
